swagger: '2.0'
info:
  title: Metadata Update
  x-ibm-name: metadata-update
  version: 1.0.0
  description: Indicate that a critical update to the metadata for Accredited Data Recipients has been made and should be obtained
schemes:
  - https
basePath: /cds-au/v1
produces:
  - application/json
consumes:
  - application/json
security:
  - clientId: []
securityDefinitions:
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - set-variable:
          version: 2.0.0
          title: set-variable
          actions:
            - set: message.headers.brand
              value: $(api.catalog.name)
              type: string
      - invoke:
          title: invoke
          version: 2.0.0
          verb: keep
          target-url: $(target-url)/cdrcache/v1/cache
          follow-redirects: false
          timeout: 60
          parameter-control:
            type: blacklist
          header-control:
            type: blacklist
            values:
              - ^X-IBM-Client-Id$
          inject-proxy-headers: true
          tls-profile: 'open-banking-tls-client-profile:1.0.0'
    catch: []
  properties: {}
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
  application-authentication:
    certificate: false
  catalogs: {}
definitions:
  RequestMetaDataUpdate:
    type: object
    required:
      - data
    properties:
      data:
        $ref: '#/definitions/RequestMetaDataUpdate_data'
      meta:
        $ref: '#/definitions/Meta'
  Meta:
    type: object
  RequestMetaDataUpdate_data:
    required:
      - action
    properties:
      action:
        type: string
        description: The action to take for the meta data. At the moment the only option is REFRESH which requires the data holder to call the ACCC to refresh meta data as soon as practicable
        default: REFRESH
        enum:
          - REFRESH
paths:
  /admin/register/metadata:
    post:
      tags:
        - Admin
        - Register
      summary: Metadata Update
      description: Indicate that a critical update to the metadata for Accredited Data Recipients has been made and should be obtained
      operationId: metadataUpdate
      parameters:
        - in: body
          name: action
          required: true
          schema:
            $ref: '#/definitions/RequestMetaDataUpdate'
        - name: x-v
          in: header
          description: Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder should respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers)
          required: true
          type: string
        - name: x-min-v
          in: header
          description: Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](##request-headers) and [x-v](##request-headers). If all versions requested are not supported then the data holder should respond with a 406 Not Acceptable.
          required: false
          type: string
      responses:
        200:
          description: Success
          headers:
            x-v:
              type: string
              description: The [version](##response-headers) of the API end point that the data holder has responded with.
      x-version: "1"
